openapi: 3.0.1
info:
  title: Offentlig Tjenestepensjon AP2025
  description: Inneholder tjenester relatert til offentlig tjenestepensjon for personer født fra og med 1963. Produsent av tjenestene er tjenestepensjonsordninger som SPK, KLP osv.
  version: 1.0.0
servers:
  - url: https://template.value/template/value
paths:
  /api/v1/tjenestepensjon/simuler:
    post:
      summary: Simuler offentlig tjenestepensjon
      description: Simulerer offentlig tjenestepensjon for brukere født fra og med 1963
      operationId: simuler
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimulerTjenestepensjonSpecV1'
        required: true
      responses:
        "200":
          description: Simulering av offentlig tjenestepensjon utført
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SimulerTjenestepensjonResultV1'

components:
  schemas:

    SimulerTjenestepensjonSpecV1:
      description: Input til tjenesten
      type: object
      required:
        - personId
        - uttaksListe
        - arIUtlandetEtter16
        - epsPensjon
        - eps2G
      properties:
        personId:
          type: string
        uttaksListe:
          type: array
          items:
            $ref: '#/components/schemas/SimulerTjenestepensjonUttakSpecV1'
        fremtidigInntektListe:
          description: Liste over brukerangitt forventet inntekt som typisk skal brukes i kall tilbake til NAV for å hente simulert AFP-beholdnning-grunnlag (for beregning av simulert AFP) og simulert folketrygdbeholdning (for beregning av APOF2020)
          type: array
          items:
            $ref: '#/components/schemas/SimulerTjenestePensjonInntektSpecV1'
        arIUtlandetEtter16:
          description: Antall år i utlandet etter 16, skal brukes for å kunne kalle tilbake til NAV for å få simulert folketrygdbeholdning for beregning av APOF2020
          type: integer
          format: int32
        epsPensjon:
          description: Om ektefelle/partner/samboer har alderspensjon, skal brukes for å kunne kalle tilbake til NAV for å få simulert folketrygdbeholdning for beregning av APOF2020
          type: boolean
        eps2G:
          description: Om ektefelle/partner/samboer har pensjonsgivende inntekt over 2G, skal brukes for å kunne kalle tilbake til NAV for å få simulert folketrygdbeholdning for beregning av APOF2020
          type: boolean

    SimulerTjenestepensjonUttakSpecV1:
      description: ønsket uttak per tjenestepensjonsytelse, dersom man ønsker alle, spesifiseres ALLE som ytelsestype
      type: object
      required:
        - ytelseType
        - fraOgMedDato
      properties:
        ytelseType:
          $ref: '#/components/schemas/SimulerTjenestepensjonYtelseTypeV1'
        fraOgMedDato:
          description: ønsket uttaksdato
          type: string
          format: date
        uttaksgrad:
          description: kun relevant for ytelser med fleksibelt uttak (for eksempel PAASLAG)
          type: integer
          format: int32

    SimulerTjenestePensjonInntektSpecV1:
      description: forventet inntekt
      type: object
      required:
        - arligInntekt
        - fraOgMedDato
      properties:
        arligInntekt:
          description: forventet inntekt fra og med gitt dato
          type: integer
          format: int32
        fraOgMedDato:
          type: string
          format: date

    SimulerTjenestepensjonResultV1:
      description: Liste over utbetalinger eller årsak til manglende utbetalinger per ytelse
      type: object
      properties:
        inkludertOrdningListe:
          description: List over TP-ordninger inkludert i simuleringen
          type: array
          items:
            $ref: '#/components/schemas/SimulerTjenestepensjonInkludertOrdningV1'
        utbetalingListe:
          description: Liste over simulert årlig og månedlig utbetaling per ytelse
          type: array
          items:
            $ref: '#/components/schemas/SimulerTjenestepensjonUtbetalingV1'
        arsakIngenUtbetaling:
          description: Liste av årsaker til at simulert beregning av tjenestepensjon feilet funksjonelt (feks avslag i vilkårsprøving)
          type: array
          items:
            $ref: '#/components/schemas/SimulerTjenestepensjonStatusV1'

    SimulerTjenestepensjonInkludertOrdningV1:
      type: object
      required:
        - tpnr
      properties:
        tpnr:
          description: TP-nummer på ordning
          type: string

    SimulerTjenestepensjonUtbetalingV1:
      type: object
      required:
        - fraOgMedDato
        - arligUtbetaling
        - manedligUtbetaling
        - ytelseType
      properties:
        fraOgMedDato:
          type: string
          format: date
        arligUtbetaling:
          type: integer
          format: int32
        manedligUtbetaling:
          type: integer
          format: int32
        ytelseType:
          $ref: '#/components/schemas/SimulerTjenestepensjonYtelseTypeV1'

    SimulerTjenestepensjonStatusV1:
      type: object
      required:
        - statusKode
        - ytelseType
      properties:
        statusKode:
          description: kode som identifiserer type logisk feil, feks vilkårsprøving av AFP Offentlig feilet på reparerbare vilkår
          type: string
        statusBeskrivelse:
          description: beskrivende tekst om logisk feil
          type: string
        ytelseType:
          $ref: '#/components/schemas/SimulerTjenestepensjonYtelseTypeV1'


    SimulerTjenestepensjonYtelseTypeV1:
      type: string
      description: Tjenestepensjonsytelser, ALLE er kun relevant i input
      enum:
        - ALDER
        - SAERALDER
        - AFP
        - UFORE
        - GJENLEVENDE
        - BARN
        - PAASLAG
        - APOF2020
        - BTP
        - OAFP
        - OT6370
        - SAERALDERSPAASLAG
        - ALLE


